import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Introduction to ROS 2',
      items: [{type: 'autogenerated', dirName: '01-intro-to-ros2'}],
    },
    {
      type: 'category',
      label: 'ROS 2 Programming',
      items: [{type: 'autogenerated', dirName: '02-ros2-programming'}],
    },
    {
      type: 'category',
      label: 'Humanoid Models',
      items: [{type: 'autogenerated', dirName: '03-humanoid-models'}],
    },
  ],
};

export default sidebars;
